MBS-11410: Remove row lock on editor table when creating edits
Reverts the following commits:

e3db4d5491c9a56f50193fd03dd67356a2c19db2
77f04ca1fe86dc53168139ef30c5b76f64bb3066

These changes were made to resolve the type of deadlock described in
MBS-3597. However, there is no longer any `edits_accepted` column on the
editor table; it's been dropped since
f4fccd56ff930b0f0610c57d2b751541fe030132 and unused since before that.
So there is no present situation I can see where the mere *creation* of
an edit requires a lock on the editor row.

More discussion of the original changes can be found here:
https://web.archive.org/web/20140602202250/http://codereview.musicbrainz.org/r/2043/

I was able to reproduce the issue in MBS-11410 simply by setting the
`statement_timeout` of my local database to something small, like '1s',
and adding a `sleep(10);` to `Data::Edit::_close`. With no `SELECT ...
FOR UPDATE` to time out on, applying this patch fixed the issue locally.

However, I'm still not clear on what caused the initial issue in the
approval edit:

    ERROR:  could not obtain lock on row in relation "edit" [for
    Statement "SELECT id FROM edit WHERE id = ? FOR UPDATE NOWAIT"
    with ParamValues: 1='77663946']

This commit does not attempt to resolve that issue, but avoids further
timeouts due to the `editor` row lock removed here.