MBS-13799: Resolve "TypeError: Object.hasOwn is not a function" (#3395)
Per https://babel.dev/docs/babel-preset-env

"It is recommended to specify the minor version otherwise "3" will be
interpreted as "3.0" which may not include polyfills for the latest features."

That would appear to be the case for `Object.hasOwn` at the very least, as
specifying the corejs version causes its polyfill to be injected (in addition
to other polyfills that weren't being included -- although `Object.hasOwn` is
the only one which I see errors on Sentry for).