MBS-14014: Drop and recreate `cover_art_archive.index_listing` (#3541)
The upgrade script for MBS-13832 currently aborts with the following error when
run against the production schema:

    ERROR:  cannot change name of view column "approved" to "filesize"
    HINT:  Use ALTER VIEW ... RENAME COLUMN ... to change name of view column instead.

This is due to MBS-14014.

Any database created on/after schema 25 (which was in 2017) will have these
filesize columns in the view already. Since this view is for internal use, the
best option is to simply drop and recreate it. (It can't be replaced without
dropping it first, as view columns can't be changed that way.)