Remove broken utf8 encoding in t/selenium.js
This causes an exception where the json5 contains non-ASCII characters:

  TypeError: Cannot read property 'length' of undefined at ucs2decode