Fix installing ultrajson from git repo using pip
This patch updates the URL to install `ultrajson` for SIR when building
`musicbrainz-tests` Docker image, fixing the following error message:

    Running command git clone -q git://github.com/esnme/ultrajson.git /tmp/pip-req-build-LKDwoT
    fatal: remote error:
      The unauthenticated git protocol on port 9418 is no longer supported.
    Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
    ERROR: Command errored out with exit status 128: git clone -q git://github.com/esnme/ultrajson.git /tmp/pip-req-build-LKDwoT Check the logs for full command output.